version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: pgvector_compose
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ai_bot
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./migrations:/migrations
    ports:
      - "5432:5432"
    restart: unless-stopped

  app:
    build: .
    dns:
      - 8.8.8.8
    container_name: bot_app_compose
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./data_pdfs:/app/data_pdfs
    command: python app.py
    restart: always

volumes:
  pgdata: